apiVersion: v1
kind: Service
metadata:
  name: news-app-service
spec:
  selector:
    app: news-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30012  # Choose any free port between 30000–32767
  type: NodePort